insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Aatrox', 'The Darkin Blade');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Ahri', 'The Nine-Tailed Fox');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Akali', 'The Rogue Assassin');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Alistar', 'The Minotaur');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Amumu', 'The Sad Mummy');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Anivia', 'The Cryophoenix');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Annie', 'The Dark Child');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Ashe', 'The Frost Archer');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Aurelion Sol', 'The Star Forger');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Azir', 'The Emperor of the Sands');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Bard', 'The Wandering Caretaker');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Blitzcrank', 'The Great Steam Golem');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Brand', 'The Burning Vengeance');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Braum', 'The Heart of the Freljord');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Caitlyn', 'The Sheriff of Piltover');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Camille', 'The Steal Shadow');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Cassiopeia', 'The Serpent''s Embrace');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Cho''Gath', 'The Terror of the Void');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Corki', 'The Daring Bombardier');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Darius', 'The Hand of Noxus');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Diana', 'Scorn of the Moon');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Dr. Mundo', 'The Madman of Zaun');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Draven', 'The Glorious Executioner');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Ekko', 'The Boy Who Shattered Time');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Elise', 'The Spider Queen');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Evelynn', 'Agony''s Embrace');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Ezreal', 'The Prodigal Explorer');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Fiddlesticks', 'The Harbinger of Doom');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Fiora', 'The Grand Duelist');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Fizz', 'The Tidal Trickster');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Galio', 'The Colossus');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Gangplank', 'The Saltwater Scourge');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Garen', 'The Might of Demacia');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Gnar', 'The Missing Link');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Gragas', 'The Rabble Rouser');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Graves', 'The Outlaw');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Hecarim', 'The Shadow of War');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Heimerdinger', 'The Revered Inventor');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Illaoi', 'The Kraken Priestess');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Irelia', 'The Blade Dancer');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Ivern', 'The Green Father');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Janna', 'The Great');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Jarvan IV', 'The Exemplar of Demacia');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Jax', 'Grandmaster at Arms');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Jayce', 'The Defender of Tomorrow');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Jhin', 'The Virtuoso');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Jinx', 'The Loose Cannon');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Kai''sa', 'Daughter of the Void');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Kalista', 'The Spear of Vengeance');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Karma', 'The Enlightened One');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Karthus', 'The Deathsinger');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Kassadin', 'The Void Walker');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Katarina', 'The Sinister Blade');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Kayle', 'The Righteous');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Kayn', 'The Shadow Reaper');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Kennen', 'The Heart of the Tempest');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Kha''Zix', 'The Voidreader');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Kindred', 'The Eternal Hunters');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Kled', 'The Cantankerous Cavalier');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Kog''Maw', 'The Mouth of the Abyss');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'LeBlanc', 'The Deceiver');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Lee Sin', 'The Blind Monk');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Leona', 'The Radiant Dawn');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Lissandra', 'The Ice Witch');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Lucian', 'The Purifier');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Lulu', 'The Fae Sorceress');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Lux', 'The Lady of Luminosity');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Malphite', 'Shard of the Monolith');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Malzahar', 'The Prophet of the Void');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Maokai', 'The Twisted Treant');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Master Yi', 'The Wuju Bladesman');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Miss Fortune', 'The Bounty Hunter');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Mordekaiser', 'The Iron Revenant');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Morgana', 'The Fallen');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Nami', 'The Tidecaller');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Nasus', 'The Curator of the Sands');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Nautilus', 'The Titan of the Depths');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Neeko', 'The Curious Chameleon');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Nidalee', 'The Bestial Huntress');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Nocturne', 'The Eternal Nightmare');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Nunu & Willump', 'The Boy and His Yeti');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Olaf', 'The Berserker');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Orianna', 'The Lady of Clockwork');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Ornn', 'The Fire Below the Mountain');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Pantheon', 'The Artisan of War');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Poppy', 'Keeper of the Hammer');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Pyke', 'The Bloodharbor Ripper');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Quinn', 'Demacia''s Wings');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Rakan', 'The Charmer');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Rammus', 'The Armordillo');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Rek''sai', 'The Void Burrower');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Renekton', 'The Butcher of the Sands');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Rengar', 'The Pridestalker');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Riven', 'The Exile');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Rumble', 'The Mechanized Menace');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Ryze', 'The Rune Mage');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Sejuani', 'Fury of the North');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Shaco', 'The Demon Jester');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Shen', 'The Eye of Twilight');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Shyvana', 'The Half-Dragon');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Singed', 'The Mad Chemist');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Sion', 'The Undead Juggernaut');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Sivir', 'The Battle Mistress');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Skarner', 'The Crystal Vanguard');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Sona', 'Maven of the Strings');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Soraka', 'The Starchild');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Swain', 'The Noxian Grand General');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Sylas', 'The Unshackled');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Syndra', 'The Dark Sovereign');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Tahm Kench', 'The River King');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Taliyah', 'The Stoneweaver');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Talon', 'The Blade''s Shadow');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Taric', 'The Shield of Valoran');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Teemo', 'The Swift Scout');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Thresh', 'The Chain Warden');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Tristana', 'The Yordle Gunner');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Trundle', 'The Troll King');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Tryndamere', 'The Barbarian King');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Twisted Fate', 'The Card Master');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Twitch', 'The Plague Rat');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Udyr', 'The Spirit Walker');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Urgot', 'The Dreadnought');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Varus', 'The Arrow of Retribution');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Vayne', 'The Night Hunter');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Veigar', 'The Tiny Master of Evil');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Vel''Koz', 'The Eye of the Void');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Vi', 'The Piltover Enforcer');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Viktor', 'The Machine Herald');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Vladimir', 'The Crimson Reaper');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Volibear', 'The Thunder''s Roar');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Warwick', 'The Uncaged Wrath of Zaun');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Wukong', 'The Monkey King');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Xayah', 'The Rebel');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Xerath', 'The Magus Ascendant');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Xin Zhao', 'The Seneschal of Demacia');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Yasuo', 'The Unforgiven');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Yorick', 'Shepherd of Souls');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Zac', 'The Secret Weapon');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Zed', 'The Master of Shadows');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Ziggs', 'The Hexplosives Expert');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Zilean', 'The Chronokeeper');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Zoe', 'The Aspect of Twilight');
insert into champions (created_at, updated_at, name, title) values (now(), now(), 'Zyra', 'Rise of the Thorns');
