delete from champions;
insert into champions (id, created_at, updated_at, name, title) values (266, now(), now(), 'Aatrox', 'The Darkin Blade');
insert into champions (id, created_at, updated_at, name, title) values (103, now(), now(), 'Ahri', 'The Nine-Tailed Fox');
insert into champions (id, created_at, updated_at, name, title) values (84, now(), now(), 'Akali', 'The Rogue Assassin');
insert into champions (id, created_at, updated_at, name, title) values (12, now(), now(), 'Alistar', 'The Minotaur');
insert into champions (id, created_at, updated_at, name, title) values (32, now(), now(), 'Amumu', 'The Sad Mummy');
insert into champions (id, created_at, updated_at, name, title) values (34, now(), now(), 'Anivia', 'The Cryophoenix');
insert into champions (id, created_at, updated_at, name, title) values (1, now(), now(), 'Annie', 'The Dark Child');
insert into champions (id, created_at, updated_at, name, title) values (22, now(), now(), 'Ashe', 'The Frost Archer');
insert into champions (id, created_at, updated_at, name, title) values (136, now(), now(), 'Aurelion Sol', 'The Star Forger');
insert into champions (id, created_at, updated_at, name, title) values (268, now(), now(), 'Azir', 'The Emperor of the Sands');
insert into champions (id, created_at, updated_at, name, title) values (432, now(), now(), 'Bard', 'The Wandering Caretaker');
insert into champions (id, created_at, updated_at, name, title) values (53, now(), now(), 'Blitzcrank', 'The Great Steam Golem');
insert into champions (id, created_at, updated_at, name, title) values (63, now(), now(), 'Brand', 'The Burning Vengeance');
insert into champions (id, created_at, updated_at, name, title) values (201, now(), now(), 'Braum', 'The Heart of the Freljord');
insert into champions (id, created_at, updated_at, name, title) values (51, now(), now(), 'Caitlyn', 'The Sheriff of Piltover');
insert into champions (id, created_at, updated_at, name, title) values (164, now(), now(), 'Camille', 'The Steal Shadow');
insert into champions (id, created_at, updated_at, name, title) values (69, now(), now(), 'Cassiopeia', 'The Serpent''s Embrace');
insert into champions (id, created_at, updated_at, name, title) values (31, now(), now(), 'Cho''Gath', 'The Terror of the Void');
insert into champions (id, created_at, updated_at, name, title) values (42, now(), now(), 'Corki', 'The Daring Bombardier');
insert into champions (id, created_at, updated_at, name, title) values (122, now(), now(), 'Darius', 'The Hand of Noxus');
insert into champions (id, created_at, updated_at, name, title) values (131, now(), now(), 'Diana', 'Scorn of the Moon');
insert into champions (id, created_at, updated_at, name, title) values (36, now(), now(), 'Dr. Mundo', 'The Madman of Zaun');
insert into champions (id, created_at, updated_at, name, title) values (119, now(), now(), 'Draven', 'The Glorious Executioner');
insert into champions (id, created_at, updated_at, name, title) values (245, now(), now(), 'Ekko', 'The Boy Who Shattered Time');
insert into champions (id, created_at, updated_at, name, title) values (60, now(), now(), 'Elise', 'The Spider Queen');
insert into champions (id, created_at, updated_at, name, title) values (28, now(), now(), 'Evelynn', 'Agony''s Embrace');
insert into champions (id, created_at, updated_at, name, title) values (81, now(), now(), 'Ezreal', 'The Prodigal Explorer');
insert into champions (id, created_at, updated_at, name, title) values (9, now(), now(), 'Fiddlesticks', 'The Harbinger of Doom');
insert into champions (id, created_at, updated_at, name, title) values (114, now(), now(), 'Fiora', 'The Grand Duelist');
insert into champions (id, created_at, updated_at, name, title) values (105, now(), now(), 'Fizz', 'The Tidal Trickster');
insert into champions (id, created_at, updated_at, name, title) values (3, now(), now(), 'Galio', 'The Colossus');
insert into champions (id, created_at, updated_at, name, title) values (41, now(), now(), 'Gangplank', 'The Saltwater Scourge');
insert into champions (id, created_at, updated_at, name, title) values (86, now(), now(), 'Garen', 'The Might of Demacia');
insert into champions (id, created_at, updated_at, name, title) values (150, now(), now(), 'Gnar', 'The Missing Link');
insert into champions (id, created_at, updated_at, name, title) values (79, now(), now(), 'Gragas', 'The Rabble Rouser');
insert into champions (id, created_at, updated_at, name, title) values (104, now(), now(), 'Graves', 'The Outlaw');
insert into champions (id, created_at, updated_at, name, title) values (120, now(), now(), 'Hecarim', 'The Shadow of War');
insert into champions (id, created_at, updated_at, name, title) values (74, now(), now(), 'Heimerdinger', 'The Revered Inventor');
insert into champions (id, created_at, updated_at, name, title) values (420, now(), now(), 'Illaoi', 'The Kraken Priestess');
insert into champions (id, created_at, updated_at, name, title) values (39, now(), now(), 'Irelia', 'The Blade Dancer');
insert into champions (id, created_at, updated_at, name, title) values (427, now(), now(), 'Ivern', 'The Green Father');
insert into champions (id, created_at, updated_at, name, title) values (40, now(), now(), 'Janna', 'The Great');
insert into champions (id, created_at, updated_at, name, title) values (59, now(), now(), 'Jarvan IV', 'The Exemplar of Demacia');
insert into champions (id, created_at, updated_at, name, title) values (24, now(), now(), 'Jax', 'Grandmaster at Arms');
insert into champions (id, created_at, updated_at, name, title) values (126, now(), now(), 'Jayce', 'The Defender of Tomorrow');
insert into champions (id, created_at, updated_at, name, title) values (202, now(), now(), 'Jhin', 'The Virtuoso');
insert into champions (id, created_at, updated_at, name, title) values (222, now(), now(), 'Jinx', 'The Loose Cannon');
insert into champions (id, created_at, updated_at, name, title) values (145, now(), now(), 'Kai''sa', 'Daughter of the Void');
insert into champions (id, created_at, updated_at, name, title) values (429, now(), now(), 'Kalista', 'The Spear of Vengeance');
insert into champions (id, created_at, updated_at, name, title) values (43, now(), now(), 'Karma', 'The Enlightened One');
insert into champions (id, created_at, updated_at, name, title) values (30, now(), now(), 'Karthus', 'The Deathsinger');
insert into champions (id, created_at, updated_at, name, title) values (38, now(), now(), 'Kassadin', 'The Void Walker');
insert into champions (id, created_at, updated_at, name, title) values (55, now(), now(), 'Katarina', 'The Sinister Blade');
insert into champions (id, created_at, updated_at, name, title) values (10, now(), now(), 'Kayle', 'The Righteous');
insert into champions (id, created_at, updated_at, name, title) values (141, now(), now(), 'Kayn', 'The Shadow Reaper');
insert into champions (id, created_at, updated_at, name, title) values (85, now(), now(), 'Kennen', 'The Heart of the Tempest');
insert into champions (id, created_at, updated_at, name, title) values (121, now(), now(), 'Kha''Zix', 'The Voidreader');
insert into champions (id, created_at, updated_at, name, title) values (203, now(), now(), 'Kindred', 'The Eternal Hunters');
insert into champions (id, created_at, updated_at, name, title) values (240, now(), now(), 'Kled', 'The Cantankerous Cavalier');
insert into champions (id, created_at, updated_at, name, title) values (96, now(), now(), 'Kog''Maw', 'The Mouth of the Abyss');
insert into champions (id, created_at, updated_at, name, title) values (7, now(), now(), 'LeBlanc', 'The Deceiver');
insert into champions (id, created_at, updated_at, name, title) values (64, now(), now(), 'Lee Sin', 'The Blind Monk');
insert into champions (id, created_at, updated_at, name, title) values (89, now(), now(), 'Leona', 'The Radiant Dawn');
insert into champions (id, created_at, updated_at, name, title) values (127, now(), now(), 'Lissandra', 'The Ice Witch');
insert into champions (id, created_at, updated_at, name, title) values (236, now(), now(), 'Lucian', 'The Purifier');
insert into champions (id, created_at, updated_at, name, title) values (117, now(), now(), 'Lulu', 'The Fae Sorceress');
insert into champions (id, created_at, updated_at, name, title) values (99, now(), now(), 'Lux', 'The Lady of Luminosity');
insert into champions (id, created_at, updated_at, name, title) values (54, now(), now(), 'Malphite', 'Shard of the Monolith');
insert into champions (id, created_at, updated_at, name, title) values (90, now(), now(), 'Malzahar', 'The Prophet of the Void');
insert into champions (id, created_at, updated_at, name, title) values (57, now(), now(), 'Maokai', 'The Twisted Treant');
insert into champions (id, created_at, updated_at, name, title) values (11, now(), now(), 'Master Yi', 'The Wuju Bladesman');
insert into champions (id, created_at, updated_at, name, title) values (21, now(), now(), 'Miss Fortune', 'The Bounty Hunter');
insert into champions (id, created_at, updated_at, name, title) values (82, now(), now(), 'Mordekaiser', 'The Iron Revenant');
insert into champions (id, created_at, updated_at, name, title) values (25, now(), now(), 'Morgana', 'The Fallen');
insert into champions (id, created_at, updated_at, name, title) values (267, now(), now(), 'Nami', 'The Tidecaller');
insert into champions (id, created_at, updated_at, name, title) values (75, now(), now(), 'Nasus', 'The Curator of the Sands');
insert into champions (id, created_at, updated_at, name, title) values (111, now(), now(), 'Nautilus', 'The Titan of the Depths');
insert into champions (id, created_at, updated_at, name, title) values (518, now(), now(), 'Neeko', 'The Curious Chameleon');
insert into champions (id, created_at, updated_at, name, title) values (76, now(), now(), 'Nidalee', 'The Bestial Huntress');
insert into champions (id, created_at, updated_at, name, title) values (56, now(), now(), 'Nocturne', 'The Eternal Nightmare');
insert into champions (id, created_at, updated_at, name, title) values (20, now(), now(), 'Nunu & Willump', 'The Boy and His Yeti');
insert into champions (id, created_at, updated_at, name, title) values (2, now(), now(), 'Olaf', 'The Berserker');
insert into champions (id, created_at, updated_at, name, title) values (61, now(), now(), 'Orianna', 'The Lady of Clockwork');
insert into champions (id, created_at, updated_at, name, title) values (516, now(), now(), 'Ornn', 'The Fire Below the Mountain');
insert into champions (id, created_at, updated_at, name, title) values (80, now(), now(), 'Pantheon', 'The Artisan of War');
insert into champions (id, created_at, updated_at, name, title) values (78, now(), now(), 'Poppy', 'Keeper of the Hammer');
insert into champions (id, created_at, updated_at, name, title) values (555, now(), now(), 'Pyke', 'The Bloodharbor Ripper');
insert into champions (id, created_at, updated_at, name, title) values (133, now(), now(), 'Quinn', 'Demacia''s Wings');
insert into champions (id, created_at, updated_at, name, title) values (246, now(), now(), 'Qiyana', 'Empress of the Elements');
insert into champions (id, created_at, updated_at, name, title) values (497, now(), now(), 'Rakan', 'The Charmer');
insert into champions (id, created_at, updated_at, name, title) values (33, now(), now(), 'Rammus', 'The Armordillo');
insert into champions (id, created_at, updated_at, name, title) values (421, now(), now(), 'Rek''sai', 'The Void Burrower');
insert into champions (id, created_at, updated_at, name, title) values (58, now(), now(), 'Renekton', 'The Butcher of the Sands');
insert into champions (id, created_at, updated_at, name, title) values (107, now(), now(), 'Rengar', 'The Pridestalker');
insert into champions (id, created_at, updated_at, name, title) values (92, now(), now(), 'Riven', 'The Exile');
insert into champions (id, created_at, updated_at, name, title) values (68, now(), now(), 'Rumble', 'The Mechanized Menace');
insert into champions (id, created_at, updated_at, name, title) values (13, now(), now(), 'Ryze', 'The Rune Mage');
insert into champions (id, created_at, updated_at, name, title) values (113, now(), now(), 'Sejuani', 'Fury of the North');
insert into champions (id, created_at, updated_at, name, title) values (35, now(), now(), 'Shaco', 'The Demon Jester');
insert into champions (id, created_at, updated_at, name, title) values (98, now(), now(), 'Shen', 'The Eye of Twilight');
insert into champions (id, created_at, updated_at, name, title) values (235, now(), now(), 'Senna', 'The Redeemer');
insert into champions (id, created_at, updated_at, name, title) values (350, now(), now(), 'Yuumi', 'The Magical Cat');
insert into champions (id, created_at, updated_at, name, title) values (523, now(), now(), 'Aphelios', 'The Weapon of the Faithful');
insert into champions (id, created_at, updated_at, name, title) values (102, now(), now(), 'Shyvana', 'The Half-Dragon');
insert into champions (id, created_at, updated_at, name, title) values (27, now(), now(), 'Singed', 'The Mad Chemist');
insert into champions (id, created_at, updated_at, name, title) values (14, now(), now(), 'Sion', 'The Undead Juggernaut');
insert into champions (id, created_at, updated_at, name, title) values (15, now(), now(), 'Sivir', 'The Battle Mistress');
insert into champions (id, created_at, updated_at, name, title) values (72, now(), now(), 'Skarner', 'The Crystal Vanguard');
insert into champions (id, created_at, updated_at, name, title) values (37, now(), now(), 'Sona', 'Maven of the Strings');
insert into champions (id, created_at, updated_at, name, title) values (16, now(), now(), 'Soraka', 'The Starchild');
insert into champions (id, created_at, updated_at, name, title) values (50, now(), now(), 'Swain', 'The Noxian Grand General');
insert into champions (id, created_at, updated_at, name, title) values (517, now(), now(), 'Sylas', 'The Unshackled');
insert into champions (id, created_at, updated_at, name, title) values (134, now(), now(), 'Syndra', 'The Dark Sovereign');
insert into champions (id, created_at, updated_at, name, title) values (223, now(), now(), 'Tahm Kench', 'The River King');
insert into champions (id, created_at, updated_at, name, title) values (163, now(), now(), 'Taliyah', 'The Stoneweaver');
insert into champions (id, created_at, updated_at, name, title) values (91, now(), now(), 'Talon', 'The Blade''s Shadow');
insert into champions (id, created_at, updated_at, name, title) values (44, now(), now(), 'Taric', 'The Shield of Valoran');
insert into champions (id, created_at, updated_at, name, title) values (17, now(), now(), 'Teemo', 'The Swift Scout');
insert into champions (id, created_at, updated_at, name, title) values (412, now(), now(), 'Thresh', 'The Chain Warden');
insert into champions (id, created_at, updated_at, name, title) values (18, now(), now(), 'Tristana', 'The Yordle Gunner');
insert into champions (id, created_at, updated_at, name, title) values (48, now(), now(), 'Trundle', 'The Troll King');
insert into champions (id, created_at, updated_at, name, title) values (23, now(), now(), 'Tryndamere', 'The Barbarian King');
insert into champions (id, created_at, updated_at, name, title) values (4, now(), now(), 'Twisted Fate', 'The Card Master');
insert into champions (id, created_at, updated_at, name, title) values (29, now(), now(), 'Twitch', 'The Plague Rat');
insert into champions (id, created_at, updated_at, name, title) values (77, now(), now(), 'Udyr', 'The Spirit Walker');
insert into champions (id, created_at, updated_at, name, title) values (6, now(), now(), 'Urgot', 'The Dreadnought');
insert into champions (id, created_at, updated_at, name, title) values (110, now(), now(), 'Varus', 'The Arrow of Retribution');
insert into champions (id, created_at, updated_at, name, title) values (67, now(), now(), 'Vayne', 'The Night Hunter');
insert into champions (id, created_at, updated_at, name, title) values (45, now(), now(), 'Veigar', 'The Tiny Master of Evil');
insert into champions (id, created_at, updated_at, name, title) values (161, now(), now(), 'Vel''Koz', 'The Eye of the Void');
insert into champions (id, created_at, updated_at, name, title) values (254, now(), now(), 'Vi', 'The Piltover Enforcer');
insert into champions (id, created_at, updated_at, name, title) values (112, now(), now(), 'Viktor', 'The Machine Herald');
insert into champions (id, created_at, updated_at, name, title) values (8, now(), now(), 'Vladimir', 'The Crimson Reaper');
insert into champions (id, created_at, updated_at, name, title) values (106, now(), now(), 'Volibear', 'The Thunder''s Roar');
insert into champions (id, created_at, updated_at, name, title) values (19, now(), now(), 'Warwick', 'The Uncaged Wrath of Zaun');
insert into champions (id, created_at, updated_at, name, title) values (62, now(), now(), 'Wukong', 'The Monkey King');
insert into champions (id, created_at, updated_at, name, title) values (498, now(), now(), 'Xayah', 'The Rebel');
insert into champions (id, created_at, updated_at, name, title) values (101, now(), now(), 'Xerath', 'The Magus Ascendant');
insert into champions (id, created_at, updated_at, name, title) values (5, now(), now(), 'Xin Zhao', 'The Seneschal of Demacia');
insert into champions (id, created_at, updated_at, name, title) values (157, now(), now(), 'Yasuo', 'The Unforgiven');
insert into champions (id, created_at, updated_at, name, title) values (83, now(), now(), 'Yorick', 'Shepherd of Souls');
insert into champions (id, created_at, updated_at, name, title) values (154, now(), now(), 'Zac', 'The Secret Weapon');
insert into champions (id, created_at, updated_at, name, title) values (238, now(), now(), 'Zed', 'The Master of Shadows');
insert into champions (id, created_at, updated_at, name, title) values (115, now(), now(), 'Ziggs', 'The Hexplosives Expert');
insert into champions (id, created_at, updated_at, name, title) values (26, now(), now(), 'Zilean', 'The Chronokeeper');
insert into champions (id, created_at, updated_at, name, title) values (142, now(), now(), 'Zoe', 'The Aspect of Twilight');
insert into champions (id, created_at, updated_at, name, title) values (143, now(), now(), 'Zyra', 'Rise of the Thorns');
